ARG DOCKER_HUB="docker.io"

FROM ${DOCKER_HUB}/alpine:3.23

RUN apk add --no-cache ca-certificates jq curl

ARG EXECUTABLE=./meowlnir
COPY $EXECUTABLE /usr/bin/meowlnir
VOLUME /data
WORKDIR /data

CMD ["/usr/bin/meowlnir"]
